title: "index"
description: "Thats me!"
permalink: /:title/
lang: "en"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
 - jekyll-feed
 - jekyll-default-layout
